[package]
name = "coord2d"
version = "0.1.9"
authors = ["abdellatif-dev <abdellatif.devlog@gmail.com>"]
description="rust lib for coordinate in 2d system"
license="MIT"
keywords = ["coord2d", "coord", "vector"]
repository = "https://github.com/abdellatif-dev/coord2d"
readme = "README.md"
exclude = [".github"]
autoexamples = true
edition = "2018"

[badges]


[dependencies]
