[package]
name = "coord2d"
version = "0.1.0"
authors = ["abdellatif-dev <abdellatif.devlog@gmail.com>"]
edition = "2018"
description="rust lib for coordinate in 2d system"
license="MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
