[package]
name = "coord2d"
version = "0.1.4"
authors = ["abdellatif-dev <abdellatif.devlog@gmail.com>"]
edition = "2018"
description="rust lib for coordinate in 2d system"
license="MIT"

[dependencies]
